config/routes.rb
# Übernommen aus "Ruby on Rails Tutorial" von Michael Hartl
SampleApp::Application.routes.draw do




  resource :addcapcosts do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
   end

  resource :capusages do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :demands do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :maxaddcaps do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :preperiods do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :prodcaps do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :products do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :segments do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :solprodstors do
     collection do
       get 'view'
       get 'data'
     end
  end

  resource :solsegs do
     collection do
       get 'view'
       get 'data'
     end
  end

  resource :storagecosts do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :storagestarts do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :timesteps do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :problems
  resources :solutions
  get "configurations/view"

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/kontakt', :to => 'pages#kontakt'
  match '/about',   :to => 'pages#about'
  match '/faq',    :to => 'pages#faq'
  match 'problems/new', :to => 'problems#new'
  match 'problems/index', :to => 'problems#index'
  match 'configurations/optimize', :to => 'configurations#optimize'
  match 'solsegs/export', :to => 'solsegs#export'
  match 'solprodstors/export', :to => 'solprodstors#export'

  root :to => 'pages#startseite'
end

app/models/problem.rb
# == Schema Information
#
# Table name: problems
#
#  id          :integer         not null, primary key
#  user_id     :integer
#  problemname :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Problem < ActiveRecord::Base
  belongs_to :user
  has_many :addcapcosts, :dependent => :destroy
  has_many :capusages, :dependent => :destroy
  has_many :demands, :dependent => :destroy
  has_many :maxaddcaps, :dependent => :destroy
  has_many :preperiods, :dependent => :destroy
  has_many :prodcaps, :dependent => :destroy
  has_many :products, :dependent => :destroy
  has_many :segments, :dependent => :destroy
  has_many :storagecosts, :dependent => :destroy
  has_many :storagestarts, :dependent => :destroy
  has_many :timesteps, :dependent => :destroy
  has_many :solprodstors, :dependent => :destroy
  has_many :solsegs, :dependent => :destroy

  validates :user_id,     :presence   => true
    validate :user_id_exists
    def user_id_exists
     if User.find_by_id(user_id)==nil
       errors.add(:base, "User muss definiert sein")
     end
    end

  validates :problemname, :uniqueness => true
  validates :problemname,  :presence   => true

  attr_accessible :user_id, :problemname
end

app/controllers/problems_controller.rb
# encoding: utf-8
# Magic Comment für deutsche Sonderzeichen
class ProblemsController < ApplicationController

  def destroy
    @problem=Problem.find(params[:id])
    if @problem==$current_problem
      $current_problem=nil
    end
    @problem.destroy
    flash[:success]='Das Problem wurde gelöscht'
    redirect_to :back
  end

  def new
     @title = "Problem anlegen"
     @problem=Problem.new
  end

  def create
     @problem=Problem.new(params[:problem])

     respond_to do |format|
       if @problem.save
         format.html {redirect_to '/problems', notice: @problem.problemname+' wurde erfolgreich erstellt.'}
         format.json {render json: @problem, status: :created, location: @problem}
       else
         format.html {render action: "new"}
         format.json {render json: @problem.errors, status: :unprocessable_entity}
       end
     end
  end

  def show
    $current_problem=Problem.find(params[:id])
    flash[:success]= $current_problem.problemname+' wurde geladen.'
    redirect_to problems_path
  end

  def index
    if $current_user==nil  #Bei direktem Aufruf von /problems zunächst auf Startseite verweisen, da sonst "called id on nil"-Fehler auftreten kann
    redirect_to root_path
    else
    @title = "Problemübersicht"
    @problems=Problem.find_all_by_user_id($current_user.id)
    end
  end


end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/index.html.erb
<% if signed_in? %>
    <h1>Problemübersicht</h1>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>

    <%if $current_problem==nil%>
    <%else%>

     <%= link_to 'Geladenes Optimierungsproblem konfigurieren', "configurations/view" %><br/>
    <%end%>
    <br/>

    <%= link_to 'Neues Optimierungsproblem anlegen', new_problem_path %>


    <br/> <br/>
    Existierende Optimierungsprobleme:
    <br/>
    <% if @problems!=nil %>

        <% @problems.each { |problems| %>
            <tr>
              <td>
                <%if problems.problemname!=nil %>
                <%= link_to problems.problemname+" laden", :controller => "problems", :action => "show", :id => problems.id %>
                <%= button_to problems.problemname+" löschen", {:controller => "problems", :action => "destroy", :id => problems.id},
                              :confirm => "Sind Sie sicher?", :method => :delete %>
                <%end%>
                <br/>
              </td>
            </tr>
        <% } %>
    <% else %>
    <% end %>

<% else %>
    <%= render 'shared/redirect_to_signin' %>
<% end %>

app/views/problems/new.html.erb
<% if signed_in? %>
    <%if @problem.errors.any?%>
        <div id="error_explanation">
          <h2><%= @problem.errors.count %>
            Fehler verhindert die Erstellung des Optimierungsproblems!</h2>
           <p>Bitte ändern Sie die Eingabe entsprechend der Fehlermeldungen:</p>
        <ul>
        <% @problem.errors.full_messages.each do |msg| %>
          <li><%= msg%></li>
          <% end %>
        </ul>
      </div>
    <% end %>

     <h1>Neues Problem benennen</h1>
     <% form_for(@problem) do |f| %>
        <div class="field">
          <%= f.label "Problemname"%><br/>
          <%= f.text_field :problemname%>
        </div>
        <div class="field">
          <%= f.label "Benutzer"%><br/>
          <%= f.collection_select(:user_id, User.all, :id, :name)%>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
     <%end%>



<% else %>
<%= render 'shared/redirect_to_signin' %>
<% end %>