config/routes.rb
# Übernommen aus "Ruby on Rails Tutorial" von Michael Hartl
SampleApp::Application.routes.draw do




  resource :addcapcosts do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
   end

  resource :capusages do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :demands do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :maxaddcaps do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :preperiods do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :prodcaps do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :products do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :segments do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :solprodstors do
     collection do
       get 'view'
       get 'data'
     end
  end

  resource :solsegs do
     collection do
       get 'view'
       get 'data'
     end
  end

  resource :storagecosts do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :storagestarts do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :timesteps do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :problems
  resources :solutions
  get "configurations/view"

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/kontakt', :to => 'pages#kontakt'
  match '/about',   :to => 'pages#about'
  match '/faq',    :to => 'pages#faq'
  match 'problems/new', :to => 'problems#new'
  match 'problems/index', :to => 'problems#index'
  match 'configurations/optimize', :to => 'configurations#optimize'
  match 'solsegs/export', :to => 'solsegs#export'
  match 'solprodstors/export', :to => 'solprodstors#export'

  root :to => 'pages#startseite'
end

app/views/pages/about.html.erb
<%# Übernommen aus "Ruby on Rails Tutorial" von Michael Hartl%>
    <h1>Informationen über diese Seite</h1>
    <p>
      Diese Seite ist im Rahmen der Vorlesungen "Entwicklung von Anwendungssystemen" und
      "Supply Chain Management and Advanced Planning Systems" an der Universität Hannover
      entstanden.
      <br/>
      <br/>
      Betreuung: Herr Prof. Dr. Stefan Helber
      <br/>
      Programmierung und Verantwortung für Webinhalte: Farid Oucherif
    </p>

app/views/pages/faq.html.erb
<%# Übernommen aus "Ruby on Rails Tutorial" von Michael Hartl%>
<h1>FAQ</h1>
<p>
  Hier finden Sie Antworten auf häufig gestellte Fragen.
  Sollten weiterhin Probleme oder Unklarheiten bestehen, so wenden Sie sich bitte an die
  <%= link_to "Kontaktadresse", kontakt_path %>.
</p>

<br/>
<br/>

<h4>Welche Voraussetzungen müssen für die erfolgreiche Nutzung dieser Applikation erfüllt sein?</h4>
Sie benötigen eine lizensierte Version der Optimierungssoftware <%= link_to "GAMS", "http://www.gams.com/" %> und
eine stabile Internet-verbindung. Empfohlen wird die Benutzung von Firefox, Internet Explorer, Opera oder Chrome.
<br/>
<br/>

<h4>Die Anmeldung gelingt, aber ich werde direkt danach wieder ausgeloggt. Was mache ich falsch?</h4>
Sie müssen die Cookies dieser Seite zulassen, damit der Anmeldestatus gespeichert werden kann. Bei den meisten Browsern
können Sie dies entsprechend einstellen.
<br/>
<br/>
<h4>Warum wird meine Dateneingabe nicht gespeichert?</h4>
Achten Sie darauf, dass Sie zunächst die Produkte, Segmente, Zeitpunkte und Vorlaufperioden definieren. Wenn Sie
ungültige Dateneingaben vornehmen, werden diese nicht gespeichert. Dazu gehören nicht definierte Produktnamen,
Segmentnamen, Zeitpunkte und Vorlaufperioden aber auch z.B. Buchstaben-eingaben bei Zeitpunkten.
Wenn ein Fehler bei der Dateneingabe auftrat, aktualisieren Sie die Seite bevor Sie weitere Dateneingaben vornehmen.
<br/>
<br/>
<h4>Wieso passen nach der Editierung von Werten die Vorschläge nicht?</h4>
Der Fehler wird behoben, indem Sie die Seite nach dem Editieren manuell aktualisieren.

<br/>
<br/>
<h4>Warum kommt beim Start der Optimierung eine Fehlermeldung?</h4>
In diesem Fall liegt sehr wahrscheinlich ein Fehler mit der Optimierungssoftware vor. Überprüfen Sie die ordnungsgemäße
Installation.
<br/>
<br/>
<h4>Wie können die Ergebnisse in Excel importiert werden?</h4>
Speichern Sie die Ausgabedateien auf Ihrem Rechner. Starten Sie dann Excel und öffnen Sie damit die Dateien. Es öffnet
sich ein Dialogfenster, dass Ihnen Importoptionen bietet. Wählen Sie als Trennzeichen das Komma aus und beenden Sie
anschließend den Dialog.

app/views/pages/kontakt.html.erb
<%# Struktur übernommen aus "Ruby on Rails Tutorial" von Michael Hartl%>
    <h1>Kontakt</h1>
    <p>
      Für Support wenden Sie sich bitte an FaridOucherif<%=no_spam%>gmail.com
    </p>

app/views/pages/startseite.html.erb
<h1>Herzlich Willkommen!</h1>

<p>
  Auf dieser Seite können Sie ganz einfach das Optimierungsproblem der kapazitierten Hauptproduktionsprogrammplanung lösen.
  Klicken Sie bitte auf "Jetzt registrieren!", um sich mit Ihrem Benutzernamen zu registrieren.
</p>

<%= link_to "Jetzt registrieren!", signup_path, :class => "signup_button round" %>