config/routes.rb
# Übernommen aus "Ruby on Rails Tutorial" von Michael Hartl
SampleApp::Application.routes.draw do




  resource :addcapcosts do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
   end

  resource :capusages do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :demands do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :maxaddcaps do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :preperiods do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :prodcaps do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :products do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :segments do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :solprodstors do
     collection do
       get 'view'
       get 'data'
     end
  end

  resource :solsegs do
     collection do
       get 'view'
       get 'data'
     end
  end

  resource :storagecosts do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :storagestarts do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :timesteps do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :problems
  resources :solutions
  get "configurations/view"

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/kontakt', :to => 'pages#kontakt'
  match '/about',   :to => 'pages#about'
  match '/faq',    :to => 'pages#faq'
  match 'problems/new', :to => 'problems#new'
  match 'problems/index', :to => 'problems#index'
  match 'configurations/optimize', :to => 'configurations#optimize'
  match 'solsegs/export', :to => 'solsegs#export'
  match 'solprodstors/export', :to => 'solprodstors#export'

  root :to => 'pages#startseite'
end

app/controllers/solutions_controller.rb
# encoding: utf-8
# Magic Comment für deutsche Sonderzeichen
class SolutionsController < ApplicationController



  def index
    @title = "Lösungsübersicht"
    if File.exist?("HPPLAN_v1_OFV.txt")
      fi=File.open("HPPLAN_v1_OFV.txt", "r")
      line=fi.readline
      fi.close
      sa=line.split
        if sa[1]!=nil                                                 #Wenn Zielfktwert vorhanden
        @objective_function_value=sa[1]                               #speichere Wert zur Ausgabe
        end
    else
    end
  end

end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/solutions/index.html.erb
<%# Struktur übernommen aus "Ruby on Rails Tutorial" von Michael Hartl%>

<% if signed_in? %>



    <h1>Lösung</h1>
    <%if $current_problem!=nil%>

    <% if File.exist?("HPPLAN_v1_OFV.txt") %>

        <h4>Der Zielfunktionswert ist <%= @objective_function_value %></h4>


        <%= link_to 'Produktion und Lagerung', view_solprodstors_path %>
        <%= button_to "Excel-Export", "/solprodstors/export"%><br/>
        <%= link_to 'Genutzte Zusatzkapazitäten', view_solsegs_path %>               <br/>
        <%= button_to "Excel-Export", "/solsegs/export"%><br/>

    <% else %>
        <h4>Das Problem konnte nicht gelöst werden!</h4>
        Entweder liegt ein Fehler in der Dateneingabe vor oder das Problem ist mit den gegebenen Restriktionen
        nicht lösbar.
    <% end %>
    <%else%>
        Laden Sie zunächst ein Problem.
    <%end%>

<% else %>
    <%= render 'shared/redirect_to_signin' %>
<% end %>