config/routes.rb
# Übernommen aus "Ruby on Rails Tutorial" von Michael Hartl
SampleApp::Application.routes.draw do




  resource :addcapcosts do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
   end

  resource :capusages do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :demands do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :maxaddcaps do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :preperiods do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :prodcaps do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :products do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :segments do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :solprodstors do
     collection do
       get 'view'
       get 'data'
     end
  end

  resource :solsegs do
     collection do
       get 'view'
       get 'data'
     end
  end

  resource :storagecosts do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :storagestarts do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resource :timesteps do
     collection do
       get 'view'
       get 'data'
       get 'dbaction'
     end
  end

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :problems
  resources :solutions
  get "configurations/view"

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/kontakt', :to => 'pages#kontakt'
  match '/about',   :to => 'pages#about'
  match '/faq',    :to => 'pages#faq'
  match 'problems/new', :to => 'problems#new'
  match 'problems/index', :to => 'problems#index'
  match 'configurations/optimize', :to => 'configurations#optimize'
  match 'solsegs/export', :to => 'solsegs#export'
  match 'solprodstors/export', :to => 'solprodstors#export'

  root :to => 'pages#startseite'
end

app/views/layouts/_footer.html.erb
<%# Struktur übernommen aus "Ruby on Rails Tutorial" von Michael Hartl%>
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Über", about_path %></li>
      <li><%= link_to "Kontakt", kontakt_path %></li>
      <li><%= link_to "FAQ", faq_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<%# Struktur übernommen aus "Ruby on Rails Tutorial" von Michael Hartl%>
<header>
  <% if signed_in? %>
  <%= link_to logo, problems_path %>
  <% else %>
  <%= link_to logo, root_path %>
  <% end %>
  <nav class="round">
    <ul>
      <% if signed_in? %>
      <li><%= link_to "Problemübersicht", problems_path %> </li>
      <li><%= link_to 'Lösungsübersicht', solutions_path%>   </li>
      <li><%= link_to "Abmelden", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Startseite", root_path %></li>
      <li><%= link_to "Anmelden", signin_path %></li>
      <% end %>
    </ul>
  </nav>

  <nav class="round">
    <ul>
      <% if signed_in? %>
          <%if $current_problem==nil%>
          <%else%>
          <li><%= link_to "Aktuell geladenes Optimierungsproblem: "+$current_problem.problemname, "/configurations/view" %> </li>
          <%end%>
      <% else %>
      <% end %>


    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%# Übernommen aus "Ruby on Rails Tutorial" von Michael Hartl%>
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<%# Übernommen aus "Ruby on Rails Tutorial" von Michael Hartl%>
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
       <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>